[project]
name = "multi-preview"
version = "1.2.29"
description = "Live multi-input image preview nodes for ComfyUI."
license = { text = "MIT License" }
requires-python = ">=3.10"
dependencies = []
classifiers = [
    "Operating System :: OS Independent",
]

[project.urls]
Repository = "https://github.com/palealloy2999-prog/comfyUI-multi-preview"
Documentation = "https://github.com/palealloy2999-prog/comfyUI-multi-preview"
Issues = "https://github.com/palealloy2999-prog/comfyUI-multi-preview/issues"

[tool.comfy]
PublisherId = "palealloy"
DisplayName = "MultiPreview"
Icon = "https://avatars.githubusercontent.com/u/230474078?s=400&v=4"
